//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanThuoc.DTO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class LoaiSanPham
    {
        [DisplayName("Mã loại thuốc")]
        public int MaLoai { get; set; }
        [DisplayName("Tên loại thuốc")]
        public string TenLoai { get; set; }
    }
}
